# Generated by Django 4.0.3 on 2024-04-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_croptype_crop_image_alter_croptype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptype',
            options={'verbose_name': 'croptype', 'verbose_name_plural': 'croptypes'},
        ),
    ]
