# Generated by Django 4.0.3 on 2024-04-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_croptype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
