# Generated by Django 5.0.4 on 2024-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nomine_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nomine_nid_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nomine_nid_picture',
            field=models.ImageField(blank=True, upload_to='nidpicture/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nomine_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nomine_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
