# Generated by Django 5.0.4 on 2024-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='roi',
            field=models.FloatField(null=True),
        ),
    ]
